language: elm
elm: "0.19.1"
node_js: "11.9"

script: make test setup_pipeline build_pipeline build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  committer-from-gh: true
  on:
    branch: master
